3.6
An error occurred while executing the following cell:
------------------
kappa = pickle.load(open("doc.p", "rb"))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m<ipython-input-2-3b938f835fd7>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mkappa[0m [0;34m=[0m [0mpickle[0m[0;34m.[0m[0mload[0m[0;34m([0m[0mopen[0m[0;34m([0m[0;34m"doc.p"[0m[0;34m,[0m [0;34m"rb"[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'doc.p'
FileNotFoundError: [Errno 2] No such file or directory: 'doc.p'

Executability                            : False
