3.5
An error occurred while executing the following cell:
------------------
import warnings
warnings.filterwarnings('ignore')
import geopandas as gpd
from shapely.geometry import Point
import matplotlib.pyplot as plt
import os
import numpy as np
import skimage.io
from operator import *
import pandas as pd

import cv2
import scipy
import matplotlib.pyplot as plt
%matplotlib inline
import skimage
import skimage.feature
import os
from sklearn.cluster import KMeans
from sklearn.cluster import MiniBatchKMeans
import xgboost
from functools import partial
import pyproj
from shapely.ops import transform
from skimage import color
from skimage import io
from collections import Counter
import xgboost

from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, Imputer
from sklearn.model_selection import cross_val_score
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
[0;32m<ipython-input-1-db3950ecaefe>[0m in [0;36m<module>[0;34m()[0m
[1;32m      1[0m [0;32mimport[0m [0mwarnings[0m[0;34m[0m[0m
[1;32m      2[0m [0mwarnings[0m[0;34m.[0m[0mfilterwarnings[0m[0;34m([0m[0;34m'ignore'[0m[0;34m)[0m[0;34m[0m[0m
[0;32m----> 3[0;31m [0;32mimport[0m [0mgeopandas[0m [0;32mas[0m [0mgpd[0m[0;34m[0m[0m
[0m[1;32m      4[0m [0;32mfrom[0m [0mshapely[0m[0;34m.[0m[0mgeometry[0m [0;32mimport[0m [0mPoint[0m[0;34m[0m[0m
[1;32m      5[0m [0;32mimport[0m [0mmatplotlib[0m[0;34m.[0m[0mpyplot[0m [0;32mas[0m [0mplt[0m[0;34m[0m[0m

[0;31mImportError[0m: No module named 'geopandas'
ImportError: No module named 'geopandas'

Executability                            : False
